In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import os 

os.chdir('../..')

BASE_DIR = os.getcwd()

properties_path = BASE_DIR + '/data/process/merge_properties_data.csv'
amenities_path = BASE_DIR + '/data/process/merged_amenities_data.csv'

In [3]:
df_properties = pd.read_csv(properties_path, index_col=False)

df_properties.head()

,id,address,total_price_millions,price_per_m2_millions,property_type,bedrooms,bathrooms,floors,area,floats
0,SA27D5,"60/15/16A số 2, P.Hiệp Bình Phước, TP.Thủ Đức,...",5600000.0,76.19,alley,2.0,2.0,2.0,73500.46,NaN
1,21JNPZ,"217 Võ Thị Sáu, Đông Hòa, Dĩ An, TP.HCM",6950000.0,96.52,alley,4.0,4.0,2.0,72005.80,NaN
2,PV5Q5G,"222/4 Nguyễn Thái Sơn, P.4, Q.Gò Vấp, TP.HCM",7120000.0,78.65,alley,3.0,2.0,2.0,90527.65,NaN
3,6Q2EG8,"Nguyễn Bình Ấp 2, Xã Phú Xuân, H.Nhà Bè, TP.HCM",3650000.0,82.95,alley,2.0,1.0,1.0,44002.41,NaN
4,3DW1EQ,"77/4 Quốc lộ 1A, P.Linh Xuân, TP.Thủ Đức, TP.HCM",4900000.0,41.88,alley,3.0,2.0,2.0,117000.96,NaN

In [4]:
df_amenities = pd.read_csv(amenities_path, index_col=False)

df_amenities.head()

,Ma_BDS,dist_min_hospital,dist_min_mall,dist_min_market,dist_min_park,dist_min_school,dist_min_supermarket,dist_median_hospital,dist_median_mall,dist_median_market,...,count_market_1km,count_park_1km,count_school_1km,count_supermarket_1km,count_hospital_2km,count_mall_2km,count_market_2km,count_park_2km,count_school_2km,count_supermarket_2km
0,SA27D5,1400.0,828.0,1800.0,10000.0,172.0,37.0,1400.0,828.0,1850.0,...,0.0,0.0,3.0,1.0,1,1,2,0,3,3
1,21JNPZ,1200.0,1600.0,1100.0,864.0,860.0,1000.0,1350.0,1600.0,1500.0,...,0.0,1.0,3.0,1.0,2,1,3,2,3,1
2,PV5Q5G,723.0,667.0,253.0,925.0,70.0,611.0,1361.5,761.0,1400.0,...,1.0,2.0,3.0,3.0,2,3,3,3,3,3
3,6Q2EG8,10000.0,10000.0,10000.0,1300.0,231.0,884.0,10000.0,10000.0,10000.0,...,0.0,0.0,3.0,2.0,0,0,0,1,3,2
4,3DW1EQ,824.0,800.0,995.0,1200.0,174.0,1000.0,1700.0,908.0,1600.0,...,1.0,0.0,3.0,1.0,3,3,3,2,3,2

In [5]:

df_final = df_properties.merge(df_amenities, left_on='id', right_on='Ma_BDS', how='left')

df_final.to_csv(BASE_DIR+'/data/process/final_dataset_for_model.csv', index=False, encoding='utf-8-sig')

In [6]:
df_final.columns

Index(['id', 'address', 'total_price_millions', 'price_per_m2_millions',
       'property_type', 'bedrooms', 'bathrooms', 'floors', 'area', 'floats',
       'Ma_BDS', 'dist_min_hospital', 'dist_min_mall', 'dist_min_market',
       'dist_min_park', 'dist_min_school', 'dist_min_supermarket',
       'dist_median_hospital', 'dist_median_mall', 'dist_median_market',
       'dist_median_park', 'dist_median_school', 'dist_median_supermarket',
       'count_hospital_1km', 'count_mall_1km', 'count_market_1km',
       'count_park_1km', 'count_school_1km', 'count_supermarket_1km',
       'count_hospital_2km', 'count_mall_2km', 'count_market_2km',
       'count_park_2km', 'count_school_2km', 'count_supermarket_2km'],
      dtype='str')

In [7]:
df_final.shape

(5842, 35)

In [8]:
df_final.isna().sum()

id                            0
address                       0
total_price_millions          0
price_per_m2_millions         0
property_type                 0
bedrooms                   3174
bathrooms                  3174
floors                     3174
area                          0
floats                     5842
Ma_BDS                      559
dist_min_hospital           559
dist_min_mall               559
dist_min_market             559
dist_min_park               559
dist_min_school             559
dist_min_supermarket        559
dist_median_hospital        559
dist_median_mall            559
dist_median_market          559
dist_median_park            559
dist_median_school          559
dist_median_supermarket     559
count_hospital_1km          559
count_mall_1km              559
count_market_1km            559
count_park_1km              559
count_school_1km            559
count_supermarket_1km       559
count_hospital_2km          559
count_mall_2km              559
count_market_2km            559
count_park_2km              559
count_school_2km            559
count_supermarket_2km       559
dtype: int64

In [9]:
df_final = df_final.drop(columns=['floats'])

In [10]:
df_final.isna().sum()

id                            0
address                       0
total_price_millions          0
price_per_m2_millions         0
property_type                 0
bedrooms                   3174
bathrooms                  3174
floors                     3174
area                          0
Ma_BDS                      559
dist_min_hospital           559
dist_min_mall               559
dist_min_market             559
dist_min_park               559
dist_min_school             559
dist_min_supermarket        559
dist_median_hospital        559
dist_median_mall            559
dist_median_market          559
dist_median_park            559
dist_median_school          559
dist_median_supermarket     559
count_hospital_1km          559
count_mall_1km              559
count_market_1km            559
count_park_1km              559
count_school_1km            559
count_supermarket_1km       559
count_hospital_2km          559
count_mall_2km              559
count_market_2km            559
count_park_2km              559
count_school_2km            559
count_supermarket_2km       559
dtype: int64

In [18]:
df_final.to_csv(BASE_DIR+'/data/process/final_dataset_for_model.csv', index=False, encoding='utf-8-sig')